### PR TITLE
Snowy's Fixes

### PR DESCRIPTION
**Pull request by GitHubEnjoyerr**
Basically fixed every issue + added a better, more faithful bed model ;)

### CODE REVIEW

**Comment by GitHubEnjoyerr** [comment]
DONT MERGE IM MAKIN A BE'ER ONE

**Comment by GitHubEnjoyerr** [comment]
Oh, and I fixed bugs that weren't in the Issues page

**Comment by GitHubEnjoyerr** [comment]
I realised that the Villager hats are pretty much impossible without modding the game. And if we're going with Optifine, we'll get a crap ton of model work, for example, Zombified Piglins.. oh, I just realised that we need to update the names of items and blocks, Hardened Clay should be Terracota.

**Comment by TheAlienDoctor** [comment]
**Changes**
(For the changelog)

- Added boat icon
- Added Jack o' lantern
- Bonemeal no longer looks like white dye
- Added zombie pigman
- Updated doors to match latest version
- Added the various types of fish
- Added tripwire hooks
- Updated sugar cane to 1.18 version
- Updated cocoa texture to 1.19

- Fixed boats
- Fixed horse's
- Fixed horse armour
- Fixed Dead bush

**Comment by TheAlienDoctor** [comment]
Thanks!

**Pull request merged**
